version: "3.3"
services:
    php:
        build:
          context: ./
          dockerfile: Dockerfile
        volumes:
          - "./td2:/var/www/html/"
        ports:
          - "80:80"
          - "3306:3306"